#!/bin/bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Dependencies
if ! command -v go &> /dev/null; then
  sudo snap install go --classic
fi

if ! command -v cargo &> /dev/null; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  source "$HOME/.cargo/env"
fi

# Programs
snap install ghostty --classic
cargo install tree-sitter-cli

# Bash
rm -rf $HOME/.bashrc
ln -s $DOTFILES/bashrc $HOME/.bashrc

# Fonts
rm -rf $HOME/.local/share/fonts
ln -s $DOTFILES/fonts $HOME/.local/share/fonts

# Git
rm -rf $HOME/.config/git
ln -s $DOTFILES/git $HOME/.config/git

# Neovim
# sudo snap install nvim --clasic
# sudo apt install ripgrep
# sudo apt install xclip
# sudo apt install build-essential
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
